@W-14781712 fix: added null checks
salesforce/formula-engine pull request #143
Opened 2024-03-29 09:09 UTC by abbasmanthirik

Added null checks for token

2024-04-01 04:59 UTC, sahil-here requested changes
We have a few queries:
**Code Change related:**
1) Why a null check has been added here for W-14781712 where EntityFormulaContextBase.createMockFieldInfo is throwing the "IllegalArgumentException: entity Info is null"? How is this check related to that exception?
**Code Quality related:**
2) Why there is a need for the "else" block?
3) Why the same check has not been added to the another constructor of the same class?
4) Why has the datatype been updated from primitive to object for location and type? If yes, then does the getter/setter need to be updated or not, has that been considered?

2024-05-02 06:01 UTC, abbasmanthirik commented
> We have a few queries: **Code Change related:**
> 
> 1. Why a null check has been added here for W-14781712 where EntityFormulaContextBase.createMockFieldInfo is throwing the "IllegalArgumentException: entity Info is null"? How is this check related to that exception?
>    **Code Quality related:**
> 2. Why there is a need for the "else" block?
> 3. Why the same check has not been added to the another constructor of the same class?
> 4. Why has the datatype been updated from primitive to object for location and type? If yes, then does the getter/setter need to be updated or not, has that been considered?

1. The actual root cause for the gack is below from the stack trace link

`
Cause0: | java.lang.NullPointerException
-- | --
Cause0-StackTrace: | at com.force.formula.impl.WrongArgumentTypeException.<init>(WrongArgumentTypeException.java:23)at com.force.formula.impl.AnnotationVisitor.verifyInputs(AnnotationVisitor.java:114)at com.force.formula.impl.AnnotationVisitor.visit(AnnotationVisitor.java:82)at com.force.formula.impl.BaseFormulaInfoImpl.visitInorderIterative(BaseFormulaInfoImpl.java:746)at com.force.formula.impl.BaseFormulaInfoImpl.visit(BaseFormulaInfoImpl.java:732)at com.force.formula.impl.BaseFormulaInfoImpl.annotateAst(BaseFormulaInfoImpl.java:484)at com.force.formula.impl.BaseFormulaInfoImpl.<init>(BaseFormulaInfoImpl.java:117)at common.formula.FormulaInfoImpl.<init>(FormulaInfoImpl.java:61)at common.formula.FormulaInfoImpl.<init>(FormulaInfoImpl.java:56)at common.formula.FormulaCoreFactory.create(FormulaCoreFactory.java:84)at com.force.formula.impl.FormulaInfoFactory.create(FormulaInfoFactory.java:89)at common.formula.template.FormulaTemplate.<init>(FormulaTemplate.java:149)
`
2. If those properties(location, type, text) are left uniinitialized without else block, there will be NPE furhter downstream
3. Done
4. Switched to primitive

2024-05-06 19:02 UTC, sahil-here commented on impl/src/main/java/com/force/formula/impl/WrongArgumentTypeException.java
>          location = token.getColumn();
Why is the "location" outside the null check here?

2024-05-07 02:46 UTC, abbasmanthirik commented on impl/src/main/java/com/force/formula/impl/WrongArgumentTypeException.java
>          location = token.getColumn();
Was a miss. Fixed it. Thanks

2024-05-08 13:10 UTC, abbasmanthirik commented on impl/src/main/java/com/force/formula/impl/WrongArgumentTypeException.java
>          location = token.getColumn();
> Why is the "location" outside the null check here?
Done

2024-05-08 19:19 UTC, sahil-here approved these changes

2024-05-24 20:27 UTC, closed without merging